# Generated by Django 4.1.3 on 2022-12-21 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hasti_Parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logop1',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
