# Generated by Django 4.1.3 on 2022-12-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hasti_Parcel', '0002_alter_logop1_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logop1',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
